
DELETE FROM CartDet
DELETE FROM Cus
DELETE FROM Rcpt
DELETE FROM RcptBuy
DELETE FROM RcptBuyDet
DELETE FROM RcptBuyStaDet
DELETE FROM RcptBuySta
DELETE FROM RcptSub
DELETE FROM RcptSubDet
DBCC CHECKIDENT (RcptBuySta, RESEED,0)
DBCC CHECKIDENT (Cart, RESEED,0)
DBCC CHECKIDENT (Rcpt, RESEED,0)

DELETE FROM ProColor
DELETE FROM ProDet
DELETE FROM ProSize
DELETE FROM ProSlide
DELETE FROM ProSlideImg
DELETE FROM Pro
DELETE FROM ProBrand
DELETE FROM ProCat
DBCC CHECKIDENT (ProColor, RESEED,0)
DBCC CHECKIDENT (ProSize, RESEED,0)
DBCC CHECKIDENT (ProSlideImg, RESEED,0)
DBCC CHECKIDENT (Pro, RESEED,0)
DBCC CHECKIDENT (ProBrand, RESEED,0)
DBCC CHECKIDENT (ProCat, RESEED,0)
DELETE FROM Shp
DBCC CHECKIDENT (Shp, RESEED,0)
DELETE FROM Sub
DBCC CHECKIDENT (Sub, RESEED,0)
DELETE FROM MstrDet 
DELETE FROM MstrRole
DELETE FROM Mstr
DBCC CHECKIDENT (MstrRole, RESEED,0)
DELETE FROM Mer
DBCC CHECKIDENT (Usr, RESEED,3)
