//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcptSub
    {
        public RcptSub()
        {
            this.SubDet = new HashSet<SubDet>();
        }
    
        public int RcptSubId { get; set; }
    
        public virtual Rcpt Rcpt { get; set; }
        public virtual ICollection<SubDet> SubDet { get; set; }
    }
}
