//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rcpt
    {
        public int RcptId { get; set; }
        public int UsrAdd { get; set; }
        public Nullable<int> UsrEdit { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        public virtual Usr Usr { get; set; }
        public virtual Usr Usr1 { get; set; }
        public virtual RcptBuy RcptBuy { get; set; }
        public virtual RcptSub RcptSub { get; set; }
    }
}
