//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcptBuyDet
    {
        public int RcptBuyId { get; set; }
        public int ShpId { get; set; }
        public int ProId { get; set; }
        public string Cmt { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual Pro Pro { get; set; }
        public virtual RcptBuy RcptBuy { get; set; }
    }
}
