//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cu
    {
        public Cu()
        {
            this.Carts = new HashSet<Cart>();
            this.RcptBuys = new HashSet<RcptBuy>();
        }
    
        public int CusId { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<RcptBuy> RcptBuys { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
