//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcptBuyStaStep
    {
        public RcptBuyStaStep()
        {
            this.RcptBuyStaDets = new HashSet<RcptBuyStaDet>();
        }
    
        public int StepId { get; set; }
        public string StepCont { get; set; }
        public Nullable<int> StepOrder { get; set; }
    
        public virtual ICollection<RcptBuyStaDet> RcptBuyStaDets { get; set; }
    }
}
