//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shp
    {
        public Shp()
        {
            this.Pros = new HashSet<Pro>();
        }
    
        public int ShpId { get; set; }
        public int MerId { get; set; }
        public string ShpName { get; set; }
        public System.DateTime DateStart { get; set; }
        public bool Active { get; set; }
    
        public virtual Mer Mer { get; set; }
        public virtual ICollection<Pro> Pros { get; set; }
    }
}
