//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usr
    {
        public Usr()
        {
            this.Rcpts = new HashSet<Rcpt>();
            this.Rcpts1 = new HashSet<Rcpt>();
        }
    
        public int UsrId { get; set; }
        public string UserName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        public virtual Cu Cu { get; set; }
        public virtual Mer Mer { get; set; }
        public virtual ICollection<Rcpt> Rcpts { get; set; }
        public virtual ICollection<Rcpt> Rcpts1 { get; set; }
        public virtual MstrRole MstrRole { get; set; }
    }
}
