//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adv
    {
        public int AdvId { get; set; }
        public string AdvName { get; set; }
        public string Desc { get; set; }
        public string ImageUrl { get; set; }
        public string Link { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Position { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
