//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public int ShpId { get; set; }
        public int CusId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<int> UsrAdd { get; set; }
        public bool IsShpChat { get; set; }
    
        public virtual ChatBox ChatBox { get; set; }
    }
}
