//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus
    {
        public Cus()
        {
            this.Cart = new HashSet<Cart>();
            this.RcptBuy = new HashSet<RcptBuy>();
        }
    
        public int CusId { get; set; }
    
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Usr Usr { get; set; }
        public virtual ICollection<RcptBuy> RcptBuy { get; set; }
    }
}
