//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kg
    {
        public int MaKg { get; set; }
        public Nullable<System.TimeSpan> GioBd { get; set; }
        public Nullable<System.TimeSpan> GioKt { get; set; }
        public string GiaCuoc { get; set; }
    }
}
