//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mer
    {
        public Mer()
        {
            this.Shp = new HashSet<Shp>();
            this.SubDet = new HashSet<SubDet>();
        }
    
        public int MerId { get; set; }
    
        public virtual ICollection<Shp> Shp { get; set; }
        public virtual ICollection<SubDet> SubDet { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
