//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr
    {
        public Mstr()
        {
            this.MstrDet = new HashSet<MstrDet>();
            this.MstrDet1 = new HashSet<MstrDet>();
        }
    
        public int MstrId { get; set; }
    
        public virtual Usr Usr { get; set; }
        public virtual ICollection<MstrDet> MstrDet { get; set; }
        public virtual ICollection<MstrDet> MstrDet1 { get; set; }
    }
}
