//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore.DataAccessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shp
    {
        public Shp()
        {
            this.ChatBox = new HashSet<ChatBox>();
            this.Pro = new HashSet<Pro>();
            this.RcptBuy = new HashSet<RcptBuy>();
        }
    
        public int ShpId { get; set; }
        public int MerId { get; set; }
        public string ShpName { get; set; }
        public System.DateTime DateStart { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ChatBox> ChatBox { get; set; }
        public virtual Mer Mer { get; set; }
        public virtual ICollection<Pro> Pro { get; set; }
        public virtual ICollection<RcptBuy> RcptBuy { get; set; }
    }
}
