<%@ Page Language="C#" Title="Quản lý sản phẩm" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ManageProduct.aspx.cs" Inherits="ShoesStore.Admin.ManageProduct" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="btn btn-lg custom_bar">Thông tin sản phẩm</div>
    <div class="row">
        <div class="col-6 table-responsive">
            <asp:GridView ID="gvProColor" class="custom_table" ShowFooter="True" runat="server" AutoGeneratedColumns="false" BorderWidth="1px" AutoGenerateColumns="False" Width="353px">
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="lbEdit" CommandArgument='<%# Eval("ColorId") %>' CommandName="EditRow" ForeColor="#8C4510" runat="server">Sửa</asp:LinkButton>
                            <asp:LinkButton ID="lbDelete" CommandArgument='<%# Eval("ColorId") %>' CommandName="DeleteRow" ForeColor="#8C4510" runat="server" CausesValidation="false">Xóa</asp:LinkButton>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:LinkButton ID="lbUpdate" CommandArgument='<%# Eval("ColorId") %>' CommandName="UpdateRow" ForeColor="#8C4510" runat="server">Cập nhật</asp:LinkButton>
                            <asp:LinkButton ID="lbCancel" CommandArgument='<%# Eval("ColorId") %>' CommandName="CancelUpdate" ForeColor="#8C4510" runat="server" CausesValidation="false">Hủy</asp:LinkButton>
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton ID="lbInsert" ValidationGroup="Insert" runat="server" CommandName="InsertRow" ForeColor="#8C4510">Thêm</asp:LinkButton>
                        </FooterTemplate>
                        <HeaderStyle Wrap="False" />
                        <ItemStyle Wrap="False" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Mã màu">
                        <ItemTemplate>
                            <%# Eval("ColorId") %>
                        </ItemTemplate>
                        <HeaderStyle Wrap="False" />
                        <ItemStyle Wrap="False" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Tên màu">
                        <ItemTemplate>
                            <%# Eval("ColorName") %>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox runat="server" ID="EditColorName" Text='<%# Bind("ColorName") %>' />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox runat="server" ID="InsertColorName" Text=' <%# Bind("ColorName") %>' />
                            <asp:RequiredFieldValidator ID="rfvEditColorName"
                                runat="server"
                                ErrorMessage="Chưa nhập tên màu"
                                ControlToValidate="InsertColorName"
                                Text="*" ForeColor="Red" ValidationGroup="Insert">
                            </asp:RequiredFieldValidator>
                        </FooterTemplate>
                        <FooterStyle Wrap="False" />
                        <HeaderStyle Wrap="False" />
                        <ItemStyle Wrap="False" />
                    </asp:TemplateField>

                </Columns>
            </asp:GridView>
            <asp:ValidationSummary ID="ValidationSummary1" ValidationGroup="Insert"
                ForeColor="Red" runat="server" />
        </div>

        <div class="col-6 table-responsive">
            <asp:GridView ID="gvBrand" class="custom_table" ShowFooter="True" runat="server" AutoGeneratedColumns="false" AutoGenerateColumns="False">
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="lbEdit" CommandArgument='<%# Eval("BrandId") %>' CommandName="EditRow" ForeColor="#8C4510" runat="server">Sửa</asp:LinkButton>
                            <asp:LinkButton ID="lbDelete" CommandArgument='<%# Eval("BrandId") %>' CommandName="DeleteRow" ForeColor="#8C4510" runat="server" CausesValidation="false">Xóa</asp:LinkButton>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:LinkButton ID="lbUpdate" CommandArgument='<%# Eval("BrandId") %>' CommandName="UpdateRow" ForeColor="#8C4510" runat="server">Cập nhật</asp:LinkButton>
                            <asp:LinkButton ID="lbCancel" CommandArgument='<%# Eval("BrandId") %>' CommandName="CancelUpdate" ForeColor="#8C4510" runat="server" CausesValidation="false">Hủy</asp:LinkButton>
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton ID="lbInsert" ValidationGroup="Insert" runat="server" CommandName="InsertRow" ForeColor="#8C4510">Thêm</asp:LinkButton>
                        </FooterTemplate>
                        <HeaderStyle />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Mã thương hiệu">
                        <ItemTemplate>
                            <%# Eval("BrandId") %>
                        </ItemTemplate>
                        <HeaderStyle />
                        <ItemStyle />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Tên thương hiệu">
                        <ItemTemplate>
                            <%# Eval("BrandName") %>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox runat="server" ID="EditColorName" Text='<%# Bind("BrandName") %>' />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox runat="server" ID="InsertBrandName" Text=' <%# Bind("BrandName") %>' />
                            <asp:RequiredFieldValidator ID="rfvEditBrandName"
                                runat="server"
                                ErrorMessage="Chưa nhập tên màu"
                                ControlToValidate="InsertBrandName"
                                Text="*" ForeColor="Red" ValidationGroup="Insert">
                            </asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>

                </Columns>
            </asp:GridView>
            <asp:ValidationSummary ID="ValidationBrand" ValidationGroup="Insert"
                ForeColor="Red" runat="server" />
        </div>
    </div>
</asp:Content>
